'use client';
import { useState } from 'react';
import { BarChart3, ChevronRight, CircleDollarSign, Loader2, MousePointerClick, ShoppingBag, X } from 'lucide-react';

export function AffiliateProductPerformance({ productId, productName }: { productId: string; productName: string }) {
  const [open,setOpen]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[data,setData]=useState<any>(null);
  async function show(){setOpen(true);if(data)return;setLoading(true);setError('');try{const r=await fetch(`/api/affiliate/products/${encodeURIComponent(productId)}/performance`,{cache:'no-store',credentials:'include'});const b=await r.json().catch(()=>({}));if(!r.ok||!b.ok)throw new Error(b.error||'No pudimos cargar el rendimiento.');setData(b);}catch(e){setError(e instanceof Error?e.message:'No pudimos cargar el rendimiento.')}finally{setLoading(false)}}
  const t=data?.totals||{clicks:0,sales:0,revenue:0,commission:0,conversion:0};
  return <><button type="button" className="performance-trigger" onClick={show}><BarChart3 size={15}/> Ver rendimiento <ChevronRight size={14}/></button>{open&&<div className="performance-modal-backdrop" role="presentation" onMouseDown={e=>{if(e.currentTarget===e.target)setOpen(false)}}><section className="performance-modal" role="dialog" aria-modal="true" aria-labelledby="performance-title"><div className="performance-modal-head"><div><span className="section-kicker">RENDIMIENTO DEL PRODUCTO</span><h2 id="performance-title">{productName}</h2><p>Resultados de tu promoción, ventas y comisiones.</p></div><button className="icon-action" type="button" onClick={()=>setOpen(false)} aria-label="Cerrar"><X size={17}/></button></div>{loading?<div className="affiliate-profile-loading"><Loader2 size={20} className="spin"/> Cargando rendimiento…</div>:error?<div className="native-error small">{error}</div>:<><div className="performance-kpi-grid"><div><MousePointerClick size={17}/><span>Clicks</span><strong>{Number(t.clicks).toLocaleString('es-VE')}</strong><small>Tracking atribuido</small></div><div><ShoppingBag size={17}/><span>Ventas</span><strong>{t.sales}</strong><small>Confirmadas</small></div><div><CircleDollarSign size={17}/><span>Facturación</span><strong>${Number(t.revenue).toFixed(2)}</strong><small>Ventas atribuidas</small></div><div><CircleDollarSign size={17}/><span>Comisión</span><strong>${Number(t.commission).toFixed(2)}</strong><small>Generada por este producto</small></div></div><div className="performance-conversion-card"><div><span>Conversión</span><strong>{Number(t.conversion).toFixed(2)}%</strong></div><div className="performance-bar"><i style={{width:`${Math.min(100,Math.max(0,Number(t.conversion)))}%`}}/></div><small>Ventas confirmadas sobre clicks registrados.</small></div><div className="modal-table-card"><div className="panel-heading"><div><span className="section-kicker">ACTIVIDAD</span><h3>Últimas ventas</h3></div><ShoppingBag size={17}/></div>{data.sales?.length?<div className="table-scroll"><table><thead><tr><th>Fecha</th><th>Facturación</th><th>Comisión</th></tr></thead><tbody>{data.sales.map((x:any)=><tr key={x.id}><td>{new Date(x.created_at).toLocaleDateString('es-VE')}</td><td>${Number(x.gross_amount||0).toFixed(2)}</td><td>${Number(x.commission_amount||0).toFixed(2)}</td></tr>)}</tbody></table></div>:<p className="modal-empty">Todavía no hay ventas confirmadas para este producto.</p>}</div></>}</section></div>}</>;
}
