"use client";
import { useState } from 'react';
import type { FormEvent } from 'react';
import { AlertCircle, CheckCircle2, Landmark, ShieldCheck } from 'lucide-react';
type Details={method?:string;bank_name?:string;account?:string;account_type?:string;holder?:string;identifier?:string;phone?:string};
export function IncomeActions({available, initialDetails}:{available:number; initialDetails:Details}){const[amount,setAmount]=useState('');const[method,setMethod]=useState(initialDetails.method||'pago_movil');const[msg,setMsg]=useState('');const[busy,setBusy]=useState(false);const[ok,setOk]=useState(false);const[details,setDetails]=useState({...initialDetails});const[editing,setEditing]=useState(false);
 const ready=Boolean(details.bank_name&&details.holder&&details.identifier&&(method==='transferencia'?details.account:details.phone));
 async function saveDetails(){setMsg('');setBusy(true);try{const r=await fetch('/api/affiliate/payout-profile',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...details,method})});const j=await r.json().catch(()=>({}));if(!r.ok||!j.ok)throw new Error(j.error||'No se pudieron guardar los datos.');setDetails(j.payout||details);setEditing(false);setOk(true);setMsg('Datos bancarios guardados correctamente.');}catch(e){setOk(false);setMsg(e instanceof Error?e.message:'No se pudieron guardar los datos.')}finally{setBusy(false)}}
 async function submit(e:FormEvent){e.preventDefault();setMsg('');setOk(false);if(!ready){setEditing(true);setMsg('Primero registra tus datos bancarios para poder solicitar un retiro.');return}const v=Number(amount);if(available<20)return setMsg('Necesitas al menos $20 disponibles para solicitar un retiro.');if(!v||v<20)return setMsg('El monto mínimo es $20.');if(v>available)return setMsg('El monto supera tu saldo disponible.');setBusy(true);const res=await fetch('/api/affiliate/payouts',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({amount:v,method:method==='transferencia'?'Transferencia':'Pago Móvil'})});const j=await res.json().catch(()=>({}));setBusy(false);setOk(res.ok);setMsg(res.ok?'Solicitud enviada correctamente.':(j.error==='PAYOUT_PROFILE_INCOMPLETE'?'Registra primero tus datos bancarios.':j.error||'No pudimos enviar la solicitud.'));if(res.ok)setAmount('');}
 const set=(k:keyof Details,v:string)=>setDetails(d=>({...d,[k]:v}));
 return <div className="income-actions-wrap">{!ready&&!editing&&<div className="payout-required-banner"><Landmark size={18}/><div><strong>Antes de solicitar un retiro</strong><p>Registra tu banco y método de pago. Administración usará estos datos para saber dónde enviarte el dinero.</p></div><button className="native-primary" type="button" onClick={()=>setEditing(true)}>Registrar datos</button></div>}
 {editing&&<div className="payout-inline-form"><div className="payout-inline-head"><div><span className="section-kicker">DATOS BANCARIOS</span><h3>¿Dónde quieres recibir tus pagos?</h3></div><ShieldCheck size={18}/></div><div className="payout-inline-grid"><label>Método<select value={method} onChange={e=>setMethod(e.target.value)}><option value="pago_movil">Pago Móvil</option><option value="transferencia">Transferencia</option></select></label><label>Banco<input value={details.bank_name||''} onChange={e=>set('bank_name',e.target.value)} /></label><label>Titular<input value={details.holder||''} onChange={e=>set('holder',e.target.value)} /></label><label>Cédula / RIF<input value={details.identifier||''} onChange={e=>set('identifier',e.target.value)} /></label>{method==='transferencia'?<><label>Número de cuenta<input value={details.account||''} onChange={e=>set('account',e.target.value)} /></label><label>Tipo de cuenta<select value={details.account_type||'Cuenta corriente'} onChange={e=>set('account_type',e.target.value)}><option>Cuenta corriente</option><option>Cuenta de ahorro</option></select></label></>:<label>Teléfono de Pago Móvil<input value={details.phone||''} onChange={e=>set('phone',e.target.value)} /></label>}</div><div className="payout-inline-actions"><button className="native-secondary" type="button" onClick={()=>setEditing(false)}>Cancelar</button><button className="native-primary" type="button" onClick={saveDetails} disabled={busy}>{busy?'Guardando…':'Guardar datos'}</button></div></div>}
 <form className="native-form income-request-form" onSubmit={submit}><div className="withdraw-amount-card"><span>Saldo disponible</span><strong>${available.toFixed(2)}</strong></div><label>Monto a retirar<input type="number" min="20" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="20.00"/></label><label>Método de cobro<select value={method} onChange={e=>setMethod(e.target.value)}><option value="pago_movil">Pago Móvil</option><option value="transferencia">Transferencia</option></select></label>{ready&&<div className="payout-destination-confirm"><CheckCircle2 size={15}/><span><strong>Destino registrado</strong>{details.bank_name} · {method==='transferencia'?details.account:details.phone}</span></div>}<button className="native-primary" disabled={busy||available<20||!ready}>{busy?'Enviando…':'Solicitar retiro'}</button>{msg&&<div className={ok?'native-success':'form-error'} role="status">{ok?<CheckCircle2 size={15}/>:<AlertCircle size={15}/>}<span>{msg}</span></div>}</form></div>}
