'use client';
import { useEffect, useState } from 'react';
import { CreditCard, Save, ShieldCheck, Smartphone } from 'lucide-react';

type Method={method:'pago_movil';enabled:boolean;bank_name:string;account:string;account_type:string;holder:string;identifier:string;phone:string};
const empty=():Method=>({method:'pago_movil',enabled:true,bank_name:'',account:'',account_type:'',holder:'',identifier:'',phone:''});

export function PaymentMethodSettings(){
 const [method,setMethod]=useState<Method>(empty()); const [paypalEnabled,setPaypalEnabled]=useState(false); const [saving,setSaving]=useState(false); const [message,setMessage]=useState('');
 useEffect(()=>{Promise.all([fetch('/api/admin/payment-methods').then(r=>r.json()),fetch('/api/checkout/paypal/config').then(r=>r.json())]).then(([manual,paypal])=>{if(manual.ok&&Array.isArray(manual.methods)){const row=manual.methods.find((x:Method)=>x.method==='pago_movil');if(row)setMethod(row)}setPaypalEnabled(Boolean(paypal.enabled));}).catch(()=>setMessage('No pudimos cargar la configuración.'))},[]);
 const update=(key:keyof Method,value:unknown)=>setMethod(v=>({...v,[key]:value}));
 async function save(){setSaving(true);setMessage('');try{const r=await fetch('/api/admin/payment-methods',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(method)});const b=await r.json().catch(()=>({}));if(!r.ok||!b.ok)throw new Error(b.message||'No se pudo guardar.');setMethod(b.method);setMessage('Pago Móvil actualizado correctamente.')}catch(e){setMessage(e instanceof Error?e.message:'No se pudo guardar.')}finally{setSaving(false)}}
 return <div className="payment-settings-grid"><section className="panel-card payment-settings-card"><div className="payment-settings-head"><div className="payment-settings-icon green"><Smartphone size={18}/></div><div><span className="section-kicker">PAGO MÓVIL</span><h3>Datos para clientes de Venezuela</h3></div><label className="payment-toggle"><input type="checkbox" checked={method.enabled} onChange={e=>update('enabled',e.target.checked)}/><span>Activo</span></label></div>
 <div className="payment-settings-fields"><label>Banco<input value={method.bank_name} onChange={e=>update('bank_name',e.target.value)} placeholder="Ej. Bancamiga (0172)" /></label><label>Nombre del titular<input value={method.holder} onChange={e=>update('holder',e.target.value)} placeholder="Titular de la cuenta" /></label><label>Cédula / RIF<input value={method.identifier} onChange={e=>update('identifier',e.target.value)} /></label><label>Teléfono<input value={method.phone} onChange={e=>update('phone',e.target.value)} /></label></div>
 <div className="payment-settings-footer"><small>Solo aparece automáticamente cuando el checkout detecta Venezuela.</small><button className="native-primary" disabled={saving} onClick={()=>void save()}><Save size={14}/>{saving?'Guardando…':'Guardar Pago Móvil'}</button></div>{message&&<div className="settings-save-message">{message}</div>}</section>
 <section className="panel-card payment-settings-card"><div className="payment-settings-head"><div className="payment-settings-icon blue"><CreditCard size={18}/></div><div><span className="section-kicker">PAYPAL</span><h3>Pago internacional</h3></div><span className={`status-pill ${paypalEnabled?'success':'warning'}`}><ShieldCheck size={13}/>{paypalEnabled?'Configurado':'Pendiente'}</span></div><div className="paypal-admin-status"><strong>{paypalEnabled?'PayPal está listo para aparecer en el Checkout.':'Añade las credenciales PayPal en las variables de entorno para habilitarlo.'}</strong><span>Variables: PAYPAL_CLIENT_ID, PAYPAL_CLIENT_SECRET y PAYPAL_BASE_URL.</span></div></section></div>
}
