'use client';

import { useState } from 'react';
import { ArrowLeft, Save } from 'lucide-react';
import { useRouter } from 'next/navigation';

type Product = { id:string; name:string; slug:string; short_description:string; description:string; price:number|string; currency:string; default_commission:number|string; landing_url:string|null; status:string };
export default function ProductEditForm({ product }: { product: Product }) {
  const router=useRouter();
  const [form,setForm]=useState({name:product.name,slug:product.slug,short_description:product.short_description||'',description:product.description||'',price:String(product.price),currency:product.currency||'USD',default_commission:String(product.default_commission),landing_url:product.landing_url||'',status:product.status||'draft'});
  const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [ok,setOk]=useState(false);
  const update=(k:keyof typeof form,v:string)=>setForm(f=>({...f,[k]:v}));
  async function save(){setBusy(true);setError('');setOk(false);try{const r=await fetch(`/api/admin/products/${product.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,price:Number(form.price),default_commission:Number(form.default_commission)})});const b=await r.json().catch(()=>({}));if(!r.ok||!b.ok)throw new Error(b.message||'No se pudo actualizar el producto.');setOk(true);router.refresh();}catch(e){setError(e instanceof Error?e.message:'No se pudo actualizar el producto.')}finally{setBusy(false)}}
  return <div className="product-edit-page"><div className="product-edit-top"><button className="native-secondary" onClick={()=>router.push(`/admin/productos/${product.id}`)}><ArrowLeft size={15}/> Volver</button><div><span className="section-kicker">PRODUCTO</span><h1>Editar producto</h1><p>Actualiza la información comercial sin perder su código de checkout ni su historial.</p></div></div><section className="panel-card product-edit-card"><div className="product-edit-grid"><label>Nombre<input value={form.name} onChange={e=>update('name',e.target.value)}/></label><label>Slug<input value={form.slug} onChange={e=>update('slug',e.target.value.toLowerCase().replace(/[^a-z0-9-]+/g,'-'))}/></label><label className="wide">Descripción corta<input value={form.short_description} onChange={e=>update('short_description',e.target.value)}/></label><label className="wide">Descripción<textarea rows={6} value={form.description} onChange={e=>update('description',e.target.value)}/></label><label>Precio<input type="number" min="0.01" step="0.01" value={form.price} onChange={e=>update('price',e.target.value)}/></label><label>Moneda<select value={form.currency} onChange={e=>update('currency',e.target.value)}><option>USD</option><option>VES</option></select></label><label>Comisión %<input type="number" min="0" max="100" step="0.01" value={form.default_commission} onChange={e=>update('default_commission',e.target.value)}/></label><label>Estado<select value={form.status} onChange={e=>update('status',e.target.value)}><option value="draft">Borrador</option><option value="active">Activo</option><option value="paused">Pausado</option><option value="archived">Archivado</option></select></label><label className="wide">Landing URL<input value={form.landing_url} onChange={e=>update('landing_url',e.target.value)} placeholder="https://..."/></label></div>{error&&<div className="native-error">{error}</div>}{ok&&<div className="native-success">Producto actualizado correctamente.</div>}<div className="product-edit-footer"><span>El checkout y el código del producto se mantienen intactos.</span><button className="native-primary" onClick={save} disabled={busy}><Save size={15}/>{busy?'Guardando…':'Guardar cambios'}</button></div></section></div>;
}
