'use client';
import { useState } from 'react';
import { CheckCircle2, FileUp, Loader2, Trash2 } from 'lucide-react';
import { createClient as createSupabaseBrowserClient } from '@/lib/supabase/browser';
type A={id:string;original_name:string|null;asset_type:string;file_size:number|null};
export function ProductDeliveryManager({productId,initialAssets}:{productId:string;initialAssets:A[]}){const[assets,setAssets]=useState(initialAssets),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 async function upload(){if(!file)return;setBusy(true);setMsg('');try{const prep=await fetch('/api/admin/products/upload',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({action:'prepare',product_id:productId,files:[{name:file.name,type:file.type,size:file.size}]})});const pb=await prep.json();if(!prep.ok||!pb.ok)throw new Error(pb.message||'No se pudo preparar el archivo.');const target=pb.uploads?.[0];if(!target)throw new Error('No recibimos autorización de subida.');const storage=createSupabaseBrowserClient();const {error}=await storage.storage.from('product-assets').uploadToSignedUrl(String(target.path),String(target.token),file,{contentType:file.type||'application/octet-stream'});if(error)throw new Error(error.message);const complete=await fetch('/api/admin/products/upload',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({action:'complete',product_id:productId,assets:[{name:file.name,path:String(target.path),asset_type:'delivery',size:file.size,mime_type:file.type||'application/octet-stream',position:assets.length}]})});const cb=await complete.json();if(!complete.ok||!cb.ok)throw new Error(cb.message||'No se pudo registrar la entrega.');setAssets(v=>[...v,cb.assets[0]]);setFile(null);setMsg('Archivo de entrega publicado correctamente.');}catch(e){setMsg(e instanceof Error?e.message:'No se pudo subir el archivo.')}finally{setBusy(false)}}
 async function remove(id:string){if(!window.confirm('¿Eliminar este recurso de entrega?'))return;setBusy(true);try{const r=await fetch(`/api/admin/products/${encodeURIComponent(productId)}/delivery-assets`,{method:'DELETE',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({asset_id:id})});const b=await r.json().catch(()=>({}));if(!r.ok||!b.ok)throw new Error(b.message||'No se pudo eliminar.');setAssets(v=>v.filter(x=>x.id!==id));setMsg('Recurso eliminado.');}catch(e){setMsg(e instanceof Error?e.message:'No se pudo eliminar.')}finally{setBusy(false)}}
 return <div className="delivery-manager"><div className="delivery-manager-head"><div><span className="section-kicker">ARCHIVOS DEL CLIENTE</span><h3>Entrega digital</h3><p>Estos archivos estarán disponibles inmediatamente en la página privada del comprador y serán enlazados en el correo de confirmación.</p></div><span className="status-pill active">{assets.length} publicados</span></div><div className="delivery-upload-row"><label className="delivery-file-input"><FileUp size={17}/><span>{file?file.name:'Seleccionar PDF, ZIP, video o recurso'}</span><input type="file" onChange={e=>setFile(e.target.files?.[0]||null)} /></label><button className="native-primary" type="button" onClick={upload} disabled={!file||busy}>{busy?<Loader2 size={15} className="spin"/>:<CheckCircle2 size={15}/>} {busy?'Procesando…':'Publicar entrega'}</button></div>{msg&&<div className="native-success small">{msg}</div>}{assets.length?<div className="delivery-asset-list">{assets.map(a=><div className="delivery-asset-row" key={a.id}><div><strong>{a.original_name||'Recurso'}</strong><small>{a.asset_type} · {a.file_size?`${Math.max(1,Math.round(a.file_size/1024))} KB`:''}</small></div><button className="icon-action danger" type="button" onClick={()=>void remove(a.id)} disabled={busy} aria-label="Eliminar"><Trash2 size={14}/></button></div>)}</div>:<div className="finance-empty-state"><FileUp size={20}/><div><strong>Sin archivos de entrega</strong><p>Publica al menos un recurso para que el comprador pueda recibirlo.</p></div></div>}</div>}
