'use client';
import { useCallback, useEffect, useState } from 'react';
import { Headphones, MessageCircle, Send, UserRound, RefreshCcw } from 'lucide-react';
type Message={id:string;thread_id:string;sender_profile_id:string|null;sender_role:'affiliate'|'admin'|'system';body:string;created_at:string};
type Thread={id:string;affiliate_id:string;status:string;created_at:string;updated_at:string;last_message_at:string|null;affiliates?:any};
function relation<T>(value:T|T[]|null|undefined):T|null{return Array.isArray(value)?value[0]??null:value??null;}
export default function SupportChat({mode}:{mode:'affiliate'|'admin'}){
 const[messages,setMessages]=useState<Message[]>([]);const[threads,setThreads]=useState<Thread[]>([]);const[selected,setSelected]=useState('');const[draft,setDraft]=useState('');const[busy,setBusy]=useState(false);const[loading,setLoading]=useState(true);const[error,setError]=useState('');
 const load=useCallback(async(threadId?:string,silent=false)=>{if(!silent)setLoading(true);try{const res=await fetch('/api/support',{cache:'no-store'});const data=await res.json().catch(()=>({}));if(!res.ok||!data.ok)throw new Error(data.error||'No se pudo cargar el soporte.');if(mode==='affiliate'){setMessages(data.messages||[]);}else{const next=data.threads||[];setThreads(next);const nextId=threadId||selected||next[0]?.id||'';if(nextId){setSelected(nextId);const mr=await fetch(`/api/support/thread/${encodeURIComponent(nextId)}`,{cache:'no-store'});const md=await mr.json().catch(()=>({}));if(mr.ok&&md.ok)setMessages(md.messages||[]);}else setMessages([]);}setError('');}catch(e){setError(e instanceof Error?e.message:'No se pudo cargar el soporte.');}finally{if(!silent)setLoading(false);}},[mode,selected]);
 useEffect(()=>{load();const id=window.setInterval(()=>load(undefined,true),5000);return()=>window.clearInterval(id);},[load]);
 async function send(){const value=draft.trim();if(!value||busy)return;setBusy(true);setError('');try{const res=await fetch('/api/support',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:value,...(mode==='admin'?{thread_id:selected}:{})})});const data=await res.json().catch(()=>({}));if(!res.ok||!data.ok)throw new Error(data.error||'No se pudo enviar el mensaje.');setDraft('');await load(selected,true);}catch(e){setError(e instanceof Error?e.message:'No se pudo enviar el mensaje.');}finally{setBusy(false);}}
 return <div className={`support-chat-shell ${mode==='admin'?'support-chat-admin':''}`}>{mode==='admin'&&<aside className="support-thread-list"><div className="support-thread-list-head"><div><span className="section-kicker">BANDEJA</span><h3>Afiliados</h3></div><button className="icon-button" onClick={()=>load()} title="Actualizar"><RefreshCcw size={15}/></button></div>{threads.length===0?<div className="support-thread-empty">No hay conversaciones todavía.</div>:threads.map(t=>{const aff=relation(t.affiliates);const profile=relation(aff?.profiles);return <button key={t.id} className={`support-thread-item ${selected===t.id?'active':''}`} onClick={()=>{setSelected(t.id);load(t.id)}}><div className="support-thread-avatar"><UserRound size={15}/></div><div><strong>{profile?.full_name||'Afiliado'}</strong><span>{aff?.affiliate_code||'—'}</span></div><small>{t.status}</small></button>})}</aside>}<section className="support-chat-panel"><div className="support-chat-head"><div className="support-chat-avatar"><Headphones size={18}/></div><div><strong>{mode==='admin'?(threads.find(t=>t.id===selected)?'Conversación con afiliado':'Selecciona una conversación'):'Soporte Rebuscándome'}</strong><span>{mode==='admin'?'Respuesta directa desde Administración':'Te responderemos por este mismo chat.'}</span></div></div><div className="support-chat-messages">{loading?<div className="support-chat-state">Cargando conversación…</div>:!messages.length?<div className="support-chat-state"><MessageCircle size={22}/><strong>{mode==='admin'?'Selecciona una conversación para comenzar.':'Escribe tu consulta para comenzar.'}</strong></div>:messages.map(m=><div key={m.id} className={`support-message ${m.sender_role}`}><div className="support-message-bubble"><p>{m.body}</p><time>{new Date(m.created_at).toLocaleString('es-VE',{dateStyle:'short',timeStyle:'short'})}</time></div></div>)}</div><div className="support-chat-compose">{error&&<div className="native-error">{error}</div>}<div className="support-chat-input-row"><textarea value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder={mode==='admin'&&!selected?'Selecciona un afiliado…':'Escribe tu mensaje…'} disabled={mode==='admin'&&!selected||busy} rows={2}/><button className="native-primary" onClick={send} disabled={busy||!draft.trim()||(mode==='admin'&&!selected)}><Send size={15}/>{busy?'Enviando…':'Enviar'}</button></div><small>Pulsa Enter para enviar. Shift + Enter crea una nueva línea.</small></div></section></div>;
}
